service: joedupuis
image: joedupuis/joedupuisio

servers:
  - filecrypt

logging:
  driver: journald

proxy:
  ssl: true
  hosts:
    - dupuis.io
    - joe.dupuis.io
  forward_headers: true
  logging:
    request_headers:
      - X-Forwarded-Proto
    response_headers:
      - X-Request-ID
  healthcheck:
    path: "/"

registry:
  username: joedupuis
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
