name: Test Docker Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: test-site:pr

      - name: Run container
        run: |
          docker run -d --name test-site -p 8080:80 test-site:pr
          # Wait for the server to start
          for i in {1..10}; do
            if curl -fs http://localhost:8080 >/dev/null; then
              echo "Server is up" && break
            fi
            sleep 1
          done

      - name: Test site response
        run: |
          curl -I http://localhost:8080 | grep '200'

      - name: Cleanup
        if: always()
        run: |
          docker rm -f test-site || true
